#!/bin/sh
set -euo pipefail

MAX_SIZE_PRETTIFY=10485760  # 10 MB
# default style to monokai if none is provided
STYLE=${1:-monokai}

TEMP_FILE="$(mktemp).html"

cat "$QUTE_TEXT" > "$TEMP_FILE"

# try GNU stat first and then OSX stat if the former fails
FILE_SIZE=$(
  stat --printf="%s" "$TEMP_FILE" 2>/dev/null ||
  stat -f%z "$TEMP_FILE" 2>/dev/null
)
if [ "$FILE_SIZE" -lt "$MAX_SIZE_PRETTIFY" ]; then
    pygmentize -f html -O full,style="$STYLE" -g <"$TEMP_FILE" >"${TEMP_FILE}_"
    mv -f "${TEMP_FILE}_" "$TEMP_FILE"
fi

# send the command to qutebrowser to open the new file containing the formatted json
echo "open -t file://$TEMP_FILE" >> "$QUTE_FIFO"
